"""add_avatar_to_candidate_profile

Revision ID: 7a0a986ca3d8
Revises: e29ea129b5fa
Create Date: 2026-06-26 10:22:10.028886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0a986ca3d8'
down_revision: Union[str, Sequence[str], None] = 'e29ea129b5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'avatar')
    # ### end Alembic commands ###
