"""add_created_at_to_candidate_profile

Revision ID: e29ea129b5fa
Revises: 43571af5331f
Create Date: 2026-06-24 14:04:02.535740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29ea129b5fa'
down_revision: Union[str, Sequence[str], None] = '43571af5331f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'created_at')
    # ### end Alembic commands ###
